### ISSUE TITLE
Klassendiagramm und Paketdiagramm

### ISSUE THREAD

**Issue by jmiegel** [jmiegel/belegarbeit_se_ii#15]

**Comment by konpel** [comment]
<img width="819" alt="klassendiaupdate" src="https://user-images.githubusercontent.com/38467640/39956067-b8294e48-55d9-11e8-89d3-68aaedf48ff3.PNG">

**Comment by konpel** [comment]
![package](https://user-images.githubusercontent.com/38467640/39960112-027a18cc-561d-11e8-9121-3880dfd0d5f9.JPG)

**Comment by konpel** [comment]
![klassendiagramm_neu](https://user-images.githubusercontent.com/38467640/41066898-e76c55f6-69e3-11e8-88b0-78650648e440.png)

**Comment by konpel** [comment]
![package_neu](https://user-images.githubusercontent.com/38467640/41067532-4421dd5a-69e6-11e8-931c-2e2b7e129896.jpg)

**Comment by konpel** [comment]
![package_neu](https://user-images.githubusercontent.com/38467640/41067668-b9babf96-69e6-11e8-9d27-40333cc349d5.jpg)

**Comment by konpel** [comment]
![package_neu](https://user-images.githubusercontent.com/38467640/41067736-f1c66a3e-69e6-11e8-9268-d2ea4cbe16c0.jpg)

**Comment by konpel** [comment]
![sequenzdiagramm](https://user-images.githubusercontent.com/38467640/41080647-cb4f39e4-6a27-11e8-8ebe-0e570167d7d1.png)

**Comment by konpel** [comment]
![sequenzdiagramm](https://user-images.githubusercontent.com/38467640/41086013-031b6792-6a39-11e8-8b36-fd2b5a0d0d1b.png)

**Comment by konpel** [comment]
![sequenz](https://user-images.githubusercontent.com/38467640/41086037-11f852c0-6a39-11e8-8ca8-b01dd0409798.jpg)

**Comment by domzim** [comment]
![sequenzdiagrammausleihen](https://user-images.githubusercontent.com/38462344/41340905-b67c141c-6ef8-11e8-84de-467bcbd84dac.PNG)
