### ISSUE TITLE
Anwendungsfalldiagramme

### ISSUE THREAD

**Issue by jmiegel** [jmiegel/belegarbeit_se_ii#2]

**Comment by milpod** [comment]
![awf-diagramm](https://user-images.githubusercontent.com/25896546/39179230-14020f90-47b4-11e8-8223-50829466763b.jpg)

**Comment by milpod** [comment]
Muss der Benutzer abstrakt sein?

**Comment by milpod** [comment]
![awf-diagramm](https://user-images.githubusercontent.com/25896546/39181054-c398fb40-47b8-11e8-9acf-b9f97448968f.jpg)

**Comment by tsandi** [comment]
Ich würde sagen das der Benutzer nicht Abstrakt ist.

**Comment by milpod** [comment]
![kd-buchausleihe](https://user-images.githubusercontent.com/25896546/39616896-e204e126-4f7d-11e8-90b5-0c2c03bec457.jpg)

**Comment by milpod** [comment]
![awf-uberblick](https://user-images.githubusercontent.com/25896546/39617038-6822e104-4f7e-11e8-8dac-0203c5f8ba26.jpg)
![kontextdiagramm allgemein](https://user-images.githubusercontent.com/25896546/39617039-683b8538-4f7e-11e8-80f6-6034008adc0f.jpg)

**Comment by milpod** [comment]
![awd](https://user-images.githubusercontent.com/25896546/39675128-0ba26604-5157-11e8-9a44-079f166784fe.jpg)
