### ISSUE TITLE
Aktivitätsdiagramme/Zustandsdiagramme

### ISSUE THREAD

**Issue by jmiegel** [jmiegel/belegarbeit_se_ii#3]

**Comment by domzim** [comment]
Updated
![aktivitat_ausleihe](https://user-images.githubusercontent.com/38462344/39356264-e0f54d52-4a0f-11e8-867b-1bae9b47ee42.JPG)
![aktivitat_ruckgabe](https://user-images.githubusercontent.com/38462344/39356265-e110435a-4a0f-11e8-885a-16047ff181b1.JPG)
![aktivitat_verlangern](https://user-images.githubusercontent.com/38462344/39356266-e12b5d2a-4a0f-11e8-9c69-15dc343b06fd.JPG)
![zustand_ausleihe](https://user-images.githubusercontent.com/38462344/39356269-e148b4a6-4a0f-11e8-9a2c-b88d88baea44.JPG)
![zustand_ruckgabe](https://user-images.githubusercontent.com/38462344/39356270-e1650b24-4a0f-11e8-807e-f664e99f7346.JPG)
![zustand_verlangern](https://user-images.githubusercontent.com/38462344/39356271-e18247e8-4a0f-11e8-86f1-1217f7badcca.JPG)

**Comment by domzim** [comment]
Update #2
![aktivitat_ausleihe](https://user-images.githubusercontent.com/38462344/39565543-ab2d24da-4eb8-11e8-8fd1-4b24a6027b51.JPG)
![aktivitat_ruckgabe](https://user-images.githubusercontent.com/38462344/39565544-ab4a37d2-4eb8-11e8-8c96-dc6c9f564b89.JPG)
![aktivitat_verlangern](https://user-images.githubusercontent.com/38462344/39565545-ab62d4e0-4eb8-11e8-8561-6bafd10a936b.JPG)
[Beschreibung Aktivitätsdiagramme.docx](https://github.com/jmiegel/belegarbeit_se_ii/files/1970023/Beschreibung.Aktivitatsdiagramme.docx)
